apiVersion: apps/{{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: acr-patch-web
  labels:
    app: {{ template "jenga.name" . }}
    chart: {{ template "jenga.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}  
spec: 
  replicas: 1 
  selector:
    matchLabels:
      app: acr-patch-web
  template: 
    metadata:
     labels:
        app: acr-patch-web
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: acr-patch-web
        image: azurecr/acr-patch-sample-web:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND
          value: acr-patch-api-svc
---
apiVersion: v1
kind: Service
metadata:
    name: acr-patch-web-svc
spec:
    ports:
        - port: 80
          protocol: TCP
          targetPort: 3000
    selector:
        app: acr-patch-web
    type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 annotations:
  kubernetes.io/ingress.class: nginx
  kubernetes.io/ingress.allow-http: "true" 
 name: acr-patch-web-ingress
 namespace: {{ .Release.Namespace }}
spec:
 rules:
  - host: acrpatch.eastus.cloudapp.azure.com 
    http:
     paths:
     - path: /
       backend:
         serviceName: acr-patch-web-svc 
         servicePort: 80